version: '3'
volumes:
  BlogDbData2:
services:
  database:
    image: "postgres:10-alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: User_mahdi
      POSTGRES_PASSWORD: 123456
      PGPASSWORD: 123456
      POSTGRES_DB: CrmDb
      PGDATA: /db_data
    volumes:
      - CrmDbData2:/db_data

