# Generated by Django 3.2.5 on 2021-07-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('price', models.PositiveIntegerField(db_index=True, default=0)),
                ('pdf_catalog', models.ImageField(upload_to='catalogs/pdf', verbose_name='عکس کاتالوگ')),
                ('img_catalog', models.FileField(upload_to='catalogs/img', verbose_name='پی دی اف کاتالوگ')),
                ('technical_features', models.TextField(max_length=500, verbose_name='ویژگی های فنی')),
                ('taxation', models.BooleanField(default=True, verbose_name='آیا مشمول مالیات می باشد ؟')),
                ('related_product', models.ManyToManyField(to='organization.OrganizationInfo', verbose_name='محصولات مرتبط')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
